package com.etoak.cxf.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.18
 * 2020-06-12T10:04:04.713+08:00
 * Generated source version: 3.1.18
 * 
 */
@WebService(targetNamespace = "http://service.cxf.etoak.com/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "list", targetNamespace = "http://service.cxf.etoak.com/", className = "com.etoak.cxf.service.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://service.cxf.etoak.com/", className = "com.etoak.cxf.service.ListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<User> list();
}
