server:
  port: 8000
spring:
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/et1911?serverTimezone=GMT
    username: root
    password: etoak

    ## 最大连接数配置
    hikari:
      maximum-pool-size: 50
  task:
    scheduling:
      pool:
        size: 20

mybatis:
  type-aliases-package: com.etoak.bean
  mapper-locations: classpath:mappers/*.xml
pagehelper:
  reasonable: true